import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {startOffice} from '../src/server.mjs';
import {hookConfig,installConfig} from '../src/connectors/setup.mjs';
import {LogObserver} from '../src/connectors/logs.mjs';
import {CrewStore} from '../src/runtime/crew.mjs';

test('setup is additive, idempotent and removes only the office hook',async t=>{
  const root=await fs.mkdtemp(path.join(os.tmpdir(),'orbit-setup-'));t.after(()=>fs.rm(root,{recursive:true,force:true}));
  await fs.mkdir(path.join(root,'.claude'));
  const original={permissions:{allow:['Read']},hooks:{Stop:[{hooks:[{type:'command',command:'my-hook'}]}]}};
  const file=path.join(root,'.claude/settings.local.json');await fs.writeFile(file,JSON.stringify(original));
  await installConfig(await hookConfig(root,'claude','office-hook'));await installConfig(await hookConfig(root,'claude','office-hook'));
  const installed=JSON.parse(await fs.readFile(file,'utf8'));assert.equal(installed.hooks.Stop.length,2);assert.deepEqual(installed.permissions,original.permissions);
  await installConfig(await hookConfig(root,'claude','office-hook',true));assert.deepEqual(JSON.parse(await fs.readFile(file,'utf8')),original);
  await fs.writeFile(file,'{broken');await assert.rejects(()=>hookConfig(root,'claude','office-hook'),/not valid JSON/);
});
test('log reader resumes partial records and merges multiple Codex files for one thread',async t=>{
  const home=await fs.mkdtemp(path.join(os.tmpdir(),'orbit-logs-'));t.after(()=>fs.rm(home,{recursive:true,force:true}));
  const root=path.join(home,'project'),dir=path.join(home,'.codex/sessions',...new Date().toISOString().slice(0,10).split('-'));await fs.mkdir(dir,{recursive:true});await fs.mkdir(root,{recursive:true});
  const file=path.join(dir,'one.jsonl'),meta={type:'session_meta',payload:{id:'thread',cwd:root}};
  const row=(type,at)=>JSON.stringify({type:'event_msg',timestamp:new Date(at).toISOString(),payload:{type,turn_id:'turn'}});
  const now=Date.now();await fs.writeFile(file,JSON.stringify(meta)+'\n'+row('task_started',now)+'\n');
  const store=new CrewStore([root]),reader=new LogObserver(home,store);await reader.poll();assert.equal(store.snapshot()[0].state,'working');
  const finish=row('task_complete',now+1);await fs.appendFile(file,finish.slice(0,30));await reader.poll();assert.equal(store.snapshot()[0].state,'working');
  await fs.appendFile(file,finish.slice(30)+'\n');await reader.poll();assert.equal(store.snapshot()[0].state,'complete');
  await fs.writeFile(path.join(dir,'two.jsonl'),JSON.stringify(meta)+'\n'+row('task_started',now+2)+'\n');reader.lastDiscovery=0;await reader.poll();assert.equal(store.snapshot().length,1);assert.equal(store.snapshot()[0].state,'working');
});
test('local server authenticates writes, limits scope, streams events and keeps private data out',async t=>{
  const home=await fs.mkdtemp(path.join(os.tmpdir(),'orbit-http-')),root=path.join(home,'project'),stateDir=path.join(home,'state');await fs.mkdir(root);
  const office=await startOffice({roots:[root],home,stateDir,port:0,observe:false});t.after(async()=>{await office.close();await fs.rm(home,{recursive:true,force:true});});
  const fetcher=(p,opt)=>fetch(office.url+p,opt);
  assert.equal((await fetcher('/')).status,200);
  assert.equal((await fetcher('/api/bootstrap',{headers:{Origin:'https://evil.example'}})).status,403);
  assert.equal((await fetcher('/api/setup/preview',{method:'POST',body:'{}'})).status,403);
  const boot=await fetcher('/api/bootstrap').then(r=>r.json());
  const hook=JSON.parse(await fs.readFile(path.join(stateDir,'server.json'),'utf8'));
  assert.ok(!JSON.stringify(boot).includes(hook.hookToken));
  const event={provider:'cursor',id:'fixture',sessionId:'live-session',cwd:root,kind:'tool-start',tool:'Write',toolId:'tool',file:path.join(root,'main.js'),arguments:'secret'};
  assert.equal((await fetcher('/api/hook',{method:'POST',headers:{authorization:'Bearer wrong'},body:JSON.stringify(event)})).status,403);
  const headers={authorization:`Bearer ${hook.hookToken}`,'content-type':'application/json'};
  await fetcher('/api/hook',{method:'POST',headers,body:JSON.stringify(event)});
  await fetcher('/api/hook',{method:'POST',headers,body:JSON.stringify(event)});
  const state=await fetcher('/api/state').then(r=>r.json());assert.equal(state.crew.length,4);assert.equal(state.executors.length,1);assert.equal(state.crew.find(c=>c.workingCount).state,'writing');assert.equal(state.executors[0].file,'main.js');assert.ok(!JSON.stringify(state).includes('secret'));
  const artifact={id:'output',artifactId:'result',revisionId:'revision-a',kind:'produced',provider:'cursor',sessionId:'live-session',cwd:root,type:'json',file:'result.json',body:'private-artifact-content'};
  assert.equal((await fetcher('/api/artifact',{method:'POST',body:JSON.stringify(artifact)})).status,403);
  assert.equal((await fetcher('/api/artifact',{method:'POST',headers,body:JSON.stringify(artifact)}).then(r=>r.json())).accepted,true);
  assert.equal((await fetcher('/api/artifact',{method:'POST',headers,body:JSON.stringify({...artifact,id:'receipt',kind:'received',handoffId:'delivery',recipientProvider:'claude',recipientSessionId:'consumer'})}).then(r=>r.json())).accepted,true);
  const plates=await fetcher('/api/state').then(r=>r.json());assert.equal(plates.artifacts[0].revisionId,'revision-a');assert.equal(plates.transfers[0].state,'received');assert.ok(!JSON.stringify(plates).includes('private-artifact-content'));
  const outside=await fetcher('/api/hook',{method:'POST',headers,body:JSON.stringify({...event,id:'outside',cwd:home})}).then(r=>r.json());assert.equal(outside.accepted,false);
  const abort=new AbortController(),stream=await fetcher('/api/events',{signal:abort.signal});const reader=stream.body.getReader();const message=await reader.read();assert.match(new TextDecoder().decode(message.value),/live-session/);abort.abort();
  const setupHeaders={'x-office-token':boot.token,'content-type':'application/json'};
  const preview=await fetcher('/api/setup/preview',{method:'POST',headers:setupHeaders,body:JSON.stringify({project:root,provider:'cursor'})}).then(r=>r.json());
  assert.equal((await fetcher('/api/setup/apply',{method:'POST',headers:setupHeaders,body:JSON.stringify({project:root,provider:'cursor',revision:'outdated'})})).status,409);
  assert.equal((await fetcher('/api/setup/apply',{method:'POST',headers:setupHeaders,body:JSON.stringify({project:root,provider:'cursor',revision:preview.revision})})).status,200);
});
